### ISSUE TITLE
デモで実現したい目標のリスト

### ISSUE THREAD

**Issue by sidestepism** [sidestepism/Vibrat-o-matic#1]
## 基本目標

- [x] Lv1 自力コントロールでできるところまでビブラートを良い感じにかける
- [x] リコーダーかける
- [x] Lv2 特定の曲について曲を再生しながらビブラート箇所で良い感じのビブラートをかける
- [x] Lv3 どんな曲についても,歌ってる最中にビブラートをかけるべきところをリアルタイムで検出しビブラートをかける
- [x] Lv4 複数人チャレンジ

## 持ち物
- [x] モニタ、HDMIケーブル
- [x] MacBook
- [x] iPad Pro
- [x] iPhone
- [x] マイク AI/F
- [x] 紙

## ToDo
- [x] ビデオ制作 (藤縄)
- [x] PureData で音程判定 (藤縄)
- [x] PureData からOSC送受信 (藤縄)
- [ ] PureData で音量を可視化 (藤縄) ←できれば
- [x] ビブラートのかかり具合を可視化 (伏見)
- [x] iPhoneで操作できるリモコンを作る (伏見)
- [x] 設定を曲ごとに保存できるようにする (伏見)
- [x] この曲やりたいという要望に応えられるようにしておく (伏見)
- [x] いい感じのプリセットを作成する (伏見)
- [x] リコーダーの練習をする (伏見)
 
## そのほか
- できたら名刺を持っていく
- 伏見は爪を切る

**Comment by sidestepism** [comment]
やったー

**Comment by sidestepism** [comment]
UISTおわりました
