### ISSUE TITLE
YouTube聴きながらRecord&Play

### ISSUE THREAD

**Issue by sidestepism** [sidestepism/Vibrat-o-matic#6]
- Youtube API Reference https://developers.google.com/youtube/js_api_reference?hl=en

曲目 #5 
- [x] I was born to love you vNhhAEupU4g
- [x] Let It Go L0MK7qz13bU
- [x] 千の風になって yqzCwcL9xDc

## todo
- [x] デフォルトの設定を保存させる
- [x] 曲目ごとに開始時刻を指定する 
- [x] ワンフレーズ歌ったら終わる
